# Generated by Django 4.2 on 2023-04-12 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('addres', models.CharField(max_length=255, verbose_name='Адрес')),
                ('facs_number', models.IntegerField()),
            ],
        ),
    ]
